# system-template.nix — seeded onto the ISO at /etc/brave-origin-templates/
# This is a standalone NixOS configuration the installer user can copy.
# It is NOT imported by the flake directly.
{ config, pkgs, lib, ... }:
# FIXME: uncomment and wire in brave-origin-nix when using as a flake module:
# { config, pkgs, lib, inputs, ... }:
{
  imports = [
    # Hardware scan generated by nixos-generate-config
    ./hardware-configuration.nix                    # FIXME: ensure this exists
  ];

  # ── Boot ─────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable      = true;      # FIXME: use grub for BIOS
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Network ───────────────────────────────────────────────────────────
  networking.hostName              = "nixos";        # FIXME
  networking.networkmanager.enable = true;

  # ── Locale ────────────────────────────────────────────────────────────
  time.timeZone      = "UTC";                        # FIXME e.g. "America/New_York"
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Xorg + Ratpoison ──────────────────────────────────────────────────
  services.xserver = {
    enable                          = true;
    windowManager.ratpoison.enable  = true;
    displayManager.startx.enable    = true;
  };

  # ── Brave Origin ──────────────────────────────────────────────────────
  # Option A: install via the flake overlay (recommended)
  # nixpkgs.overlays = [ inputs.brave-origin-nix.overlays.default ];
  # environment.systemPackages = [ pkgs.brave-origin ];
  #
  # Option B: use the NixOS module (handles security wrapper automatically)
  # imports = [ inputs.brave-origin-nix.nixosModules.brave-origin ];
  # programs.brave-origin.enable = true;

  # ── Packages ──────────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [
    git
    curl
    htop
    xterm
    dejavu_fonts
  ];

  # ── Users ─────────────────────────────────────────────────────────────
  users.users.user = {                               # FIXME: your username
    isNormalUser   = true;
    extraGroups    = [ "wheel" "networkmanager" "video" "audio" ];
    initialPassword = "changeme";                    # FIXME: set a real password
  };

  # ── home-manager (optional) ───────────────────────────────────────────
  # programs.home-manager.enable = true;

  # ── Nix settings ──────────────────────────────────────────────────────
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "25.05";                     # FIXME: match your nixpkgs
}
