# /etc/nixos/flake.nix — seed from /etc/brave-origin-templates/
# Copy this whole directory to /mnt/etc/nixos/ then run nixos-install.
#
# brave-origin and all packages are fetched from the internet during
# nixos-install — nothing needs to be on the ISO itself.
#
# Adjust the FIXME markers before running nixos-install.
# ──────────────────────────────────────────────────────────────────────
# THIS FILE IS ACTUALLY flake.nix — rename it when you copy it:
#   cp /etc/brave-origin-templates/configuration.nix /mnt/etc/nixos/flake.nix
# ──────────────────────────────────────────────────────────────────────
{
  description = "NixOS system with Brave Origin";

  inputs = {
    nixpkgs.url          = "github:NixOS/nixpkgs/nixos-unstable";
    brave-origin-nix.url = "github:legendarymsr/brave-origin-nix";
    brave-origin-nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, brave-origin-nix }:
  {
    nixosConfigurations.system = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./hardware-configuration.nix     # generated by nixos-generate-config
        brave-origin-nix.nixosModules.brave-origin
        brave-origin-nix.nixosModules.nixvim   # Neovim (Tokyo Night, tree-sitter)
        ({ config, pkgs, lib, ... }: {

          # ── Boot ──────────────────────────────────────────────────────
          boot.loader.systemd-boot.enable      = true;   # FIXME: grub for BIOS
          boot.loader.efi.canTouchEfiVariables = true;

          # Uncomment for ZFS support (fetched during install, not on ISO)
          # boot.supportedFilesystems = [ "zfs" ];
          # boot.zfs.extraPools       = [ "tank" ];      # FIXME: your pool name

          # ── Network ───────────────────────────────────────────────────
          networking.hostName              = "nixos";    # FIXME
          networking.networkmanager.enable = true;

          # ── Locale ────────────────────────────────────────────────────
          time.timeZone      = "UTC";                    # FIXME
          i18n.defaultLocale = "en_US.UTF-8";

          # ── Brave Origin ──────────────────────────────────────────────
          # Installed on the target system during nixos-install (not on ISO).
          programs.brave-origin.enable = true;

          # ── Xorg + Ratpoison ──────────────────────────────────────────
          services.xserver = {
            enable                         = true;
            windowManager.ratpoison.enable = true;
          };

          # ── Users ─────────────────────────────────────────────────────
          users.users.user = {             # FIXME: your username
            isNormalUser   = true;
            extraGroups    = [ "wheel" "networkmanager" "video" "audio" ];
            initialPassword = "changeme"; # FIXME: change after first login
          };

          # ── Packages ──────────────────────────────────────────────────
          environment.systemPackages = with pkgs; [
            git curl htop xterm dejavu_fonts
          ];

          # ── Nix ───────────────────────────────────────────────────────
          nix.settings.experimental-features = [ "nix-command" "flakes" ];

          system.stateVersion = "25.05";   # FIXME: match your nixpkgs branch
        })
      ];
    };
  };
}
